branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        # Marketplace plugins require version bump for ANY change
        # Default: feat=minor, fix=patch, perf=patch, revert=patch
        # Added: all other types trigger patch release
        - { type: "docs", release: "patch" }
        - { type: "chore", release: "patch" }
        - { type: "style", release: "patch" }
        - { type: "refactor", release: "patch" }
        - { type: "test", release: "patch" }
        - { type: "build", release: "patch" }
        - { type: "ci", release: "patch" }
        - { type: "revert", release: "patch" }
  - "@semantic-release/release-notes-generator"
  # ADR/Design Spec links + version sync via @semantic-release/exec
  # ADR: 2025-12-06-release-notes-adr-linking
  # ADR: 2025-12-05-centralized-version-management
  - - "@semantic-release/exec"
    # All documentation changes in release notes
    # ADR: 2025-12-06-release-notes-adr-linking
    - generateNotesCmd: 'node plugins/itp/skills/semantic-release/scripts/generate-doc-notes.mjs ${lastRelease.gitTag}'
      prepareCmd: "node scripts/sync-versions.mjs ${nextRelease.version}"
  - "@semantic-release/changelog"
  # marketplace.json-only versioning: no individual plugin.json files
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - plugin.json
        - package.json
        - .claude-plugin/plugin.json
        - .claude-plugin/marketplace.json
        - plugins/itp-hooks/plugin.json
      message: "chore(release): ${nextRelease.version} [skip ci]"
  - "@semantic-release/github"
