branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        # Marketplace plugins require version bump for ANY change
        # Default: feat=minor, fix=patch, perf=patch, revert=patch
        # Added: all other types trigger patch release
        - { type: "docs", release: "patch" }
        - { type: "chore", release: "patch" }
        - { type: "style", release: "patch" }
        - { type: "refactor", release: "patch" }
        - { type: "test", release: "patch" }
        - { type: "build", release: "patch" }
        - { type: "ci", release: "patch" }
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  # Version sync via custom script (more reliable than replace-plugin)
  # ADR: 2025-12-05-centralized-version-management
  - - "@semantic-release/exec"
    - prepareCmd: "node scripts/sync-versions.mjs ${nextRelease.version}"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - plugin.json
        - package.json
        - .claude-plugin/plugin.json
        - .claude-plugin/marketplace.json
        - "plugins/*/.claude-plugin/plugin.json"
      message: "chore(release): ${nextRelease.version} [skip ci]"
  - "@semantic-release/github"
