branches:
  - main

plugins:
  # Preflight: Block release if working directory is dirty
  # ADR: 2025-12-23-semantic-release-preflight-guard
  - - "@semantic-release/exec"
    - verifyConditionsCmd: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "❌ PREFLIGHT FAILED: Working directory not clean"
          echo "Uncommitted changes:"
          git status --short
          echo ""
          echo "Please commit or stash changes before release."
          exit 1
        fi
        echo "✓ Working directory clean"
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        # Marketplace plugins require version bump for ANY change
        # Default: feat=minor, fix=patch, perf=patch, revert=patch
        # Added: all other types trigger patch release
        - { type: "docs", release: "patch" }
        - { type: "chore", release: "patch" }
        - { type: "style", release: "patch" }
        - { type: "refactor", release: "patch" }
        - { type: "test", release: "patch" }
        - { type: "build", release: "patch" }
        - { type: "ci", release: "patch" }
        - { type: "revert", release: "patch" }
  - "@semantic-release/release-notes-generator"
  # ADR/Design Spec links + version sync via @semantic-release/exec
  # ADR: 2025-12-06-release-notes-adr-linking
  # ADR: 2025-12-05-centralized-version-management
  - - "@semantic-release/exec"
    # All documentation changes in release notes
    # ADR: 2025-12-06-release-notes-adr-linking
    - generateNotesCmd: 'node plugins/itp/skills/semantic-release/scripts/generate-doc-notes.mjs ${lastRelease.gitTag}'
      prepareCmd: "node scripts/sync-versions.mjs ${nextRelease.version}"
  - "@semantic-release/changelog"
  # marketplace.json-only versioning: no individual plugin.json files
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - plugin.json
        - package.json
        - .claude-plugin/plugin.json
        - .claude-plugin/marketplace.json
        - plugins/itp-hooks/plugin.json
      message: "chore(release): ${nextRelease.version} [skip ci]"
  # Push commit and tags after @semantic-release/git creates them
  # Belt-and-suspenders: ensures push happens even in --no-ci mode
  - - "@semantic-release/exec"
    - successCmd: "/usr/bin/env bash -c 'git push --follow-tags origin main && git update-index --refresh && echo ✓ Git index refreshed'"
  - "@semantic-release/github"
  # Post-release: Auto-update local plugin and verify cache
  # Fully automated - no manual intervention required
  - - "@semantic-release/exec"
    - successCmd: |
        /usr/bin/env bash << 'VERIFY_PLUGIN_EOF'
        set -euo pipefail

        echo ""
        echo "═══════════════════════════════════════════════════════════"
        echo "  POST-RELEASE: Automated Plugin Update & Verification"
        echo "═══════════════════════════════════════════════════════════"

        VERSION="${nextRelease.version}"
        CACHE_DIR="$HOME/.claude/plugins/cache/cc-skills"
        MARKETPLACE_DIR="$HOME/.claude/plugins/marketplaces/cc-skills"

        # Step 1: Update marketplace git repo (source of truth)
        echo "→ Step 1: Updating marketplace repo..."
        if [[ -d "$MARKETPLACE_DIR/.git" ]]; then
          cd "$MARKETPLACE_DIR"
          git fetch origin --tags --quiet
          git reset --hard "v$VERSION" --quiet 2>/dev/null || git reset --hard origin/main --quiet
          REPO_VERSION=$(jq -r '.version' plugin.json 2>/dev/null || echo "unknown")
          if [[ "$REPO_VERSION" == "$VERSION" ]]; then
            echo "  ✓ Marketplace repo updated to v$VERSION"
          else
            echo "  ✗ FAILED: Marketplace repo at v$REPO_VERSION, expected v$VERSION"
            exit 1
          fi
        else
          echo "  ⚠ Marketplace repo not found at $MARKETPLACE_DIR"
        fi

        # Step 2: Trigger Claude Code plugin update via CLI
        echo "→ Step 2: Triggering Claude Code plugin update..."
        if command -v claude &>/dev/null; then
          # Use claude CLI in non-interactive mode to update plugin
          claude --print "/plugin update cc-skills" 2>&1 | head -20 || true
          echo "  ✓ Plugin update triggered"
        else
          echo "  ⚠ Claude CLI not found in PATH, skipping automatic update"
        fi

        # Step 3: Wait briefly for cache to populate
        sleep 2

        # Step 4: Verify cache has new version
        echo "→ Step 3: Verifying plugin cache..."
        if [[ -d "$CACHE_DIR" ]]; then
          # Find any plugin directory to check versions
          SAMPLE_PLUGIN=$(ls -1 "$CACHE_DIR" 2>/dev/null | head -1)
          if [[ -n "$SAMPLE_PLUGIN" && -d "$CACHE_DIR/$SAMPLE_PLUGIN/$VERSION" ]]; then
            echo "  ✓ Cache verified: v$VERSION present"
          elif [[ -n "$SAMPLE_PLUGIN" ]]; then
            LATEST_CACHED=$(ls -1 "$CACHE_DIR/$SAMPLE_PLUGIN" 2>/dev/null | sort -V | tail -1)
            if [[ "$LATEST_CACHED" == "$VERSION" ]]; then
              echo "  ✓ Cache verified: v$VERSION is latest"
            else
              echo "  ⚠ Cache has v$LATEST_CACHED, v$VERSION may need session restart"
            fi
          fi
        fi

        # Step 5: Final verification - check installed_plugins.json
        echo "→ Step 4: Checking installed plugins manifest..."
        INSTALLED_JSON="$HOME/.claude/plugins/installed_plugins.json"
        if [[ -f "$INSTALLED_JSON" ]]; then
          # Use variable for jq filter to avoid quoting issues in YAML
          JQ_FILTER='.[] | select(.marketplace == "cc-skills") | .version'
          INSTALLED_VERSION=$(jq -r "$JQ_FILTER" "$INSTALLED_JSON" 2>/dev/null | head -1)
          if [[ "$INSTALLED_VERSION" == "$VERSION" ]]; then
            echo "  ✓ installed_plugins.json shows v$VERSION"
          elif [[ -n "$INSTALLED_VERSION" ]]; then
            echo "  ⚠ installed_plugins.json shows v$INSTALLED_VERSION"
          fi
        fi

        echo ""
        echo "═══════════════════════════════════════════════════════════"
        echo "  ✓ Post-release verification complete for v$VERSION"
        echo "═══════════════════════════════════════════════════════════"
        VERIFY_PLUGIN_EOF
