branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - prepareCmd: |
        # Update version in plugin.json files
        sed -i '' 's/"version": "[^"]*"/"version": "${nextRelease.version}"/' plugin.json
        sed -i '' 's/"version": "[^"]*"/"version": "${nextRelease.version}"/' .claude-plugin/plugin.json
        sed -i '' 's/"version": "[^"]*"/"version": "${nextRelease.version}"/' .claude-plugin/marketplace.json
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - plugin.json
        - package.json
        - .claude-plugin/plugin.json
        - .claude-plugin/marketplace.json
      message: "chore(release): ${nextRelease.version} [skip ci]"
  - "@semantic-release/github"
