branches:
  - main

plugins:
  # Preflight: Block release if working directory is dirty
  # ADR: 2025-12-23-semantic-release-preflight-guard
  - - "@semantic-release/exec"
    - verifyConditionsCmd: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "❌ PREFLIGHT FAILED: Working directory not clean"
          echo "Uncommitted changes:"
          git status --short
          echo ""
          echo "Please commit or stash changes before release."
          exit 1
        fi
        echo "✓ Working directory clean"
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        # Marketplace plugins require version bump for ANY change
        # Default: feat=minor, fix=patch, perf=patch, revert=patch
        # Added: all other types trigger patch release
        - { type: "docs", release: "patch" }
        - { type: "chore", release: "patch" }
        - { type: "style", release: "patch" }
        - { type: "refactor", release: "patch" }
        - { type: "test", release: "patch" }
        - { type: "build", release: "patch" }
        - { type: "ci", release: "patch" }
        - { type: "revert", release: "patch" }
  - "@semantic-release/release-notes-generator"
  # ADR/Design Spec links + version sync via @semantic-release/exec
  # ADR: 2025-12-06-release-notes-adr-linking
  # ADR: 2025-12-05-centralized-version-management
  - - "@semantic-release/exec"
    # All documentation changes in release notes
    # ADR: 2025-12-06-release-notes-adr-linking
    - generateNotesCmd: 'node plugins/itp/skills/semantic-release/scripts/generate-doc-notes.mjs ${lastRelease.gitTag}'
      prepareCmd: "node scripts/sync-versions.mjs ${nextRelease.version}"
  - "@semantic-release/changelog"
  # marketplace.json-only versioning: no individual plugin.json files
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - plugin.json
        - package.json
        - .claude-plugin/plugin.json
        - .claude-plugin/marketplace.json
        - plugins/itp-hooks/plugin.json
      message: "chore(release): ${nextRelease.version} [skip ci]"
  # Push commit and tags after @semantic-release/git creates them
  # Belt-and-suspenders: ensures push happens even in --no-ci mode
  - - "@semantic-release/exec"
    - successCmd: "/usr/bin/env bash -c 'git push --follow-tags origin main && git update-index --refresh && echo ✓ Git index refreshed'"
  - "@semantic-release/github"
  # Post-release: Update local plugin installation and verify cache
  # Ensures developer's own Claude Code instance has the latest version
  - - "@semantic-release/exec"
    - successCmd: |
        /usr/bin/env bash << 'VERIFY_PLUGIN_EOF'
        echo ""
        echo "═══════════════════════════════════════════════════════════"
        echo "  POST-RELEASE: Plugin Cache Verification"
        echo "═══════════════════════════════════════════════════════════"

        VERSION="${nextRelease.version}"
        CACHE_DIR="$HOME/.claude/plugins/cache/cc-skills"
        MARKETPLACE_DIR="$HOME/.claude/plugins/marketplaces/cc-skills"

        # Step 1: Update marketplace git repo
        if [[ -d "$MARKETPLACE_DIR/.git" ]]; then
          echo "→ Updating marketplace repo..."
          cd "$MARKETPLACE_DIR"
          git fetch origin --tags --quiet
          git reset --hard "v$VERSION" --quiet 2>/dev/null || git reset --hard origin/main --quiet
          echo "  ✓ Marketplace repo at v$VERSION"
        fi

        # Step 2: Check cache for new version
        echo "→ Checking plugin cache..."
        CACHED_VERSIONS=$(ls -1 "$CACHE_DIR/ralph/" 2>/dev/null | sort -V | tail -3 | tr '\n' ' ')
        echo "  Recent cached versions: $CACHED_VERSIONS"

        if [[ -d "$CACHE_DIR/ralph/$VERSION" ]]; then
          echo "  ✓ Cache already has v$VERSION"
        else
          echo "  ⚠ Cache missing v$VERSION - will be created on next /plugin update"
        fi

        # Step 3: Verification summary
        echo ""
        echo "───────────────────────────────────────────────────────────"
        echo "  To ensure Claude Code uses v$VERSION, run:"
        echo "    /plugin update cc-skills"
        echo "  Then restart Claude Code session"
        echo "───────────────────────────────────────────────────────────"
        VERIFY_PLUGIN_EOF
