#!/usr/bin/env bash
# bootstrap-claude-session.sh - Template for pre-Claude session setup
# Generated by /asciinema-tools:bootstrap
#
# Usage: source this script, then run 'claude'
#   source bootstrap-claude-session.sh && claude
#
# This is a TEMPLATE file. The actual script is generated with
# embedded configuration from /asciinema-tools:bootstrap command.

set -euo pipefail

# Configuration (populated by /asciinema-tools:bootstrap)
REPO_URL="${REPO_URL:-}"
BRANCH="${BRANCH:-asciinema-recordings}"
IDLE_THRESHOLD="${IDLE_THRESHOLD:-30}"
ZSTD_LEVEL="${ZSTD_LEVEL:-3}"
WORKSPACE="${WORKSPACE:-$(basename "$PWD")}"
DATETIME="${DATETIME:-$(date +%Y-%m-%d_%H-%M)}"
CAST_FILE="${CAST_FILE:-$PWD/tmp/${WORKSPACE}_${DATETIME}.cast}"
LOCAL_RECORDINGS="${LOCAL_RECORDINGS:-$HOME/asciinema_recordings/$(basename "$REPO_URL" .git)}"

# Validate configuration
if [[ -z "$REPO_URL" ]]; then
  echo "ERROR: REPO_URL not configured. Run /asciinema-tools:bootstrap first."
  exit 1
fi

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  asciinema-tools BOOTSTRAP - Pre-Claude Session Setup      ║"
echo "╠════════════════════════════════════════════════════════════╣"

# 1. Ensure directories
mkdir -p "$PWD/tmp"
mkdir -p "$LOCAL_RECORDINGS/chunks"

# 2. Clone/update orphan branch
if [[ ! -d "$LOCAL_RECORDINGS/.git" ]]; then
  echo "║  [1/4] Cloning orphan branch...                            ║"
  git clone --single-branch --branch "$BRANCH" --depth 1 "$REPO_URL" "$LOCAL_RECORDINGS"
else
  echo "║  [1/4] Updating orphan branch...                           ║"
  git -C "$LOCAL_RECORDINGS" pull --ff-only 2>/dev/null || true
fi

# 3. Start asciinema recording
echo "║  [2/4] Starting asciinema recording...                      ║"
echo "║        Output: $CAST_FILE"

# Record in background - uses a subshell to avoid blocking
asciinema rec --stdin "$CAST_FILE" &
ASCIINEMA_PID=$!

# 4. Start idle-chunker in background
echo "║  [3/4] Starting idle-chunker (${IDLE_THRESHOLD}s threshold)...              ║"
(
  cd "$LOCAL_RECORDINGS"
  last_pos=0
  while [[ -f "$CAST_FILE" ]] || sleep 2; do
    [[ -f "$CAST_FILE" ]] || continue

    # Get file modification time and size
    if [[ "$(uname)" == "Darwin" ]]; then
      mtime=$(stat -f%m "$CAST_FILE" 2>/dev/null || echo 0)
      size=$(stat -f%z "$CAST_FILE" 2>/dev/null || echo 0)
    else
      mtime=$(stat -c%Y "$CAST_FILE" 2>/dev/null || echo 0)
      size=$(stat -c%s "$CAST_FILE" 2>/dev/null || echo 0)
    fi

    idle=$(($(date +%s) - mtime))

    if (( idle >= IDLE_THRESHOLD && size > last_pos )); then
      chunk="chunks/chunk_$(date +%Y%m%d_%H%M%S).cast"
      tail -c +$((last_pos + 1)) "$CAST_FILE" > "$chunk"
      zstd -"${ZSTD_LEVEL}" --rm "$chunk" 2>/dev/null
      git add chunks/ 2>/dev/null
      git commit -m "chunk $(date +%H:%M)" 2>/dev/null
      git push 2>/dev/null
      last_pos=$size
      echo "[$(date +%H:%M:%S)] Chunk pushed to GitHub"
    fi
    sleep 5
  done
) &
CHUNKER_PID=$!

# 5. Trap EXIT for cleanup
cleanup() {
  echo ""
  echo "╔════════════════════════════════════════════════════════════╗"
  echo "║  BOOTSTRAP CLEANUP - Finalizing recording...               ║"
  echo "╠════════════════════════════════════════════════════════════╣"

  # Stop asciinema gracefully
  if [[ -n "${ASCIINEMA_PID:-}" ]]; then
    kill -INT "$ASCIINEMA_PID" 2>/dev/null || true
  fi

  # Wait for final chunk
  sleep 2
  if [[ -n "${CHUNKER_PID:-}" ]]; then
    kill "$CHUNKER_PID" 2>/dev/null || true
  fi

  # Push any remaining data
  cd "$LOCAL_RECORDINGS"
  if [[ -f "$CAST_FILE" ]]; then
    final_chunk="chunks/final_$(date +%Y%m%d_%H%M%S).cast"
    cp "$CAST_FILE" "$final_chunk"
    zstd -"${ZSTD_LEVEL}" --rm "$final_chunk" 2>/dev/null
    git add chunks/ 2>/dev/null
    git commit -m "final chunk" 2>/dev/null
    git push 2>/dev/null
  fi

  echo "║  Recording finalized and pushed to GitHub                  ║"
  echo "║  GitHub Actions will recompress to brotli archive          ║"
  echo "╚════════════════════════════════════════════════════════════╝"
}
trap cleanup EXIT

echo "║  [4/4] Ready! Recording and streaming active.               ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║                                                             ║"
echo "║  PIDs:                                                      ║"
echo "║    asciinema: $ASCIINEMA_PID"
echo "║    chunker:   $CHUNKER_PID"
echo "║                                                             ║"
echo "║  Now run: claude                                            ║"
echo "║  Everything you do will stream to GitHub automatically.     ║"
echo "╚════════════════════════════════════════════════════════════╝"
