#!/usr/bin/env bash
# bootstrap-claude-session.sh - Start asciinema recording session
# Generated by /asciinema-tools:bootstrap
#
# Chunking is handled by the launchd daemon (idle-chunker-daemon.sh)
# This script only starts the recording - the daemon watches for new .cast files.
#
# USAGE: ./bootstrap-claude-session.sh (NOT source)
#
# ADR: /docs/adr/2025-12-26-asciinema-daemon-architecture.md

# ============================================================================
# SOURCE PREVENTION GUARD
# ============================================================================
# This script MUST be executed directly, not sourced.
# Sourcing would cause the EXIT trap to fire in the caller's shell.

if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
    echo "ERROR: This script must be executed directly, not sourced."
    echo ""
    echo "Wrong:   source ${BASH_SOURCE[0]}"
    echo "Correct: ./${BASH_SOURCE[0]##*/}"
    echo ""
    echo "Reason: Sourcing this script would cause the EXIT trap to fire"
    echo "        when your shell exits, not when the recording ends."
    return 1
fi

# ============================================================================
# SHELL OPTIONS
# ============================================================================
# Note: NO -e (errexit) - causes problems with asciinema exit codes

set -uo pipefail

# ============================================================================
# CONFIGURATION (populated by /asciinema-tools:bootstrap)
# ============================================================================

REPO_URL="${REPO_URL:-}"
BRANCH="${BRANCH:-asciinema-recordings}"
LOCAL_REPO="${LOCAL_REPO:-}"
WORKSPACE="${WORKSPACE:-$(basename "$PWD")}"
DATETIME="${DATETIME:-$(date +%Y-%m-%d_%H-%M)}"

# Recording location - daemon watches ~/.asciinema/active/
ASCIINEMA_DIR="$HOME/.asciinema"
ACTIVE_DIR="$ASCIINEMA_DIR/active"
CAST_FILE="$ACTIVE_DIR/${WORKSPACE}_${DATETIME}.cast"
CONFIG_FILE="${CAST_FILE%.cast}.json"

# ============================================================================
# VALIDATION
# ============================================================================

if [[ -z "$REPO_URL" ]]; then
    echo "ERROR: REPO_URL not configured."
    echo "Run /asciinema-tools:bootstrap to generate a configured script."
    exit 1
fi

if [[ -z "$LOCAL_REPO" ]]; then
    LOCAL_REPO="$HOME/asciinema_recordings/$(basename "${REPO_URL%.git}")"
fi

# ============================================================================
# PREFLIGHT CHECKS
# ============================================================================

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  asciinema Recording Session                                   ║"
echo "╠════════════════════════════════════════════════════════════════╣"

# Check daemon is running
if ! launchctl list 2>/dev/null | grep -q "asciinema-chunker"; then
    echo "║  WARNING: Daemon not running!                                  ║"
    echo "║  Chunks will NOT be pushed to GitHub.                          ║"
    echo "║  Run: /asciinema-tools:daemon-start                            ║"
    echo "╠════════════════════════════════════════════════════════════════╣"
fi

# ============================================================================
# CLEAR SSH CACHES
# ============================================================================
# Prevent stale ControlMaster connections from causing auth failures

echo "║  [1/4] Clearing SSH caches...                                  ║"
rm -f ~/.ssh/control-* 2>/dev/null || true
ssh -O exit git@github.com 2>/dev/null || true
ssh -O exit -p 443 git@ssh.github.com 2>/dev/null || true

# ============================================================================
# CREATE DIRECTORIES
# ============================================================================

echo "║  [2/4] Setting up directories...                               ║"
if ! mkdir -p "$ACTIVE_DIR"; then
    echo "ERROR: Failed to create active recordings directory: $ACTIVE_DIR" >&2
    echo "Tip: Check permissions and available disk space" >&2
    exit 1
fi
if ! mkdir -p "$LOCAL_REPO/chunks"; then
    echo "ERROR: Failed to create chunks directory: $LOCAL_REPO/chunks" >&2
    echo "Tip: Check permissions and available disk space" >&2
    exit 1
fi

# ============================================================================
# WRITE CONFIG FOR DAEMON
# ============================================================================
# The daemon reads this to know where to push chunks

echo "║  [3/4] Writing recording config...                             ║"
cat > "$CONFIG_FILE" <<EOF
{
    "repo_url": "$REPO_URL",
    "branch": "$BRANCH",
    "local_repo": "$LOCAL_REPO",
    "workspace": "$WORKSPACE",
    "started": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF

# ============================================================================
# CLEANUP ON EXIT
# ============================================================================

cleanup() {
    echo ""
    echo "╔════════════════════════════════════════════════════════════════╗"
    echo "║  Recording Session Ended                                       ║"
    echo "╠════════════════════════════════════════════════════════════════╣"
    echo "║  Recording saved to: $CAST_FILE"
    echo "║  The daemon will push the final chunk automatically.           ║"
    echo "║                                                                ║"
    echo "║  Check status: /asciinema-tools:daemon-status                  ║"
    echo "╚════════════════════════════════════════════════════════════════╝"
}
trap cleanup EXIT

# ============================================================================
# START RECORDING
# ============================================================================

echo "║  [4/4] Starting asciinema recording...                         ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo "║                                                                ║"
echo "║  You are now in an asciinema recording session.                ║"
echo "║  Type 'claude' to start Claude Code.                           ║"
echo "║                                                                ║"
echo "║  To end: exit Claude (Ctrl+D), then type 'exit' again.         ║"
echo "║  The daemon will push chunks automatically.                    ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# BLOCKING COMMAND - user works inside asciinema's subshell
# When user exits, script continues and EXIT trap fires
asciinema rec --stdin "$CAST_FILE"
