#import "FloatingClockStarterProfiles.h"

// v4 iter-55: every starter profile now covers every profileManagedKey.
// Prior profiles omitted ~12 v4 keys (ShowFlags, ShowUTCReference,
// ShowSkyState, Density, LayoutMode, SegmentGap, CornerStyle,
// ShadowStyle, ProgressBarStyle, ActiveFontSize, NextFontSize,
// DateFormat). activateProfile only writes keys it finds, so switching
// to "Default" used to leave the missing keys at the user's current
// value — not a real factory reset. Fully specified here so each
// profile has a coherent identity.
NSDictionary *buildStarterProfiles(void) {
    return @{
        @"Default": @{
            @"DisplayMode": @"three-segment",
            @"LocalTheme": @"terminal",
            @"ActiveTheme": @"green_phosphor",
            @"NextTheme": @"soft_glass",
            @"ColorTheme": @"terminal",
            @"FontSize": @24.0,
            @"ActiveFontSize": @11.0,
            @"NextFontSize": @11.0,
            @"ShowSeconds": @YES,
            @"ShowDate": @YES,
            @"DateFormat": @"short",
            @"TimeFormat": @"24h",
            @"CanvasOpacity": @0.75,
            @"ActiveBarCells": @40,
            @"NextItemCount": @3,
            @"ProgressBarStyle": @"dots",
            @"LayoutMode": @"stacked-local-top",
            @"SegmentGap": @"normal",
            @"CornerStyle": @"rounded",
            @"ShadowStyle": @"none",
            @"Density": @"default",
            @"ShowFlags": @YES,
            @"ShowUTCReference": @YES,
            @"ShowSkyState": @YES,
            @"ShowProgressPercent": @NO,
            @"SelectedMarket": @"local",
        },
        @"Day Trader": @{
            @"DisplayMode": @"three-segment",
            @"LocalTheme": @"amber_crt",
            @"ActiveTheme": @"amber_crt",
            @"NextTheme": @"amber_crt",
            @"ColorTheme": @"amber_crt",
            @"FontSize": @32.0,
            @"ActiveFontSize": @14.0,
            @"NextFontSize": @14.0,
            @"ShowSeconds": @YES,
            @"ShowDate": @NO,
            @"DateFormat": @"short",
            @"TimeFormat": @"24h",
            @"CanvasOpacity": @1.00,
            @"ActiveBarCells": @12,
            @"NextItemCount": @5,
            @"ProgressBarStyle": @"blocks",
            @"LayoutMode": @"stacked-local-top",
            @"SegmentGap": @"tight",
            @"CornerStyle": @"sharp",
            @"ShadowStyle": @"none",
            @"Density": @"compact",
            @"ShowFlags": @YES,
            @"ShowUTCReference": @YES,
            @"ShowSkyState": @NO,
            @"ShowProgressPercent": @NO,
            @"SelectedMarket": @"nyse",
        },
        @"Night Owl": @{
            @"DisplayMode": @"local-only",
            @"LocalTheme": @"soft_glass",
            @"ActiveTheme": @"soft_glass",
            @"NextTheme": @"soft_glass",
            @"ColorTheme": @"soft_glass",
            @"FontSize": @16.0,
            @"ActiveFontSize": @11.0,
            @"NextFontSize": @11.0,
            @"ShowSeconds": @YES,
            @"ShowDate": @NO,
            @"DateFormat": @"short",
            @"TimeFormat": @"24h",
            @"CanvasOpacity": @0.50,
            @"ActiveBarCells": @40,
            @"NextItemCount": @3,
            @"ProgressBarStyle": @"dots",
            @"LayoutMode": @"stacked-local-top",
            @"SegmentGap": @"airy",
            @"CornerStyle": @"rounded",
            @"ShadowStyle": @"subtle",
            @"Density": @"comfortable",
            @"ShowFlags": @NO,
            @"ShowUTCReference": @NO,
            @"ShowSkyState": @YES,
            @"ShowProgressPercent": @NO,
            @"SelectedMarket": @"local",
        },
        @"Minimalist": @{
            @"DisplayMode": @"local-only",
            @"LocalTheme": @"high_contrast",
            @"ActiveTheme": @"high_contrast",
            @"NextTheme": @"high_contrast",
            @"ColorTheme": @"high_contrast",
            @"FontSize": @20.0,
            @"ActiveFontSize": @11.0,
            @"NextFontSize": @11.0,
            @"ShowSeconds": @NO,
            @"ShowDate": @NO,
            @"DateFormat": @"short",
            @"TimeFormat": @"24h",
            @"CanvasOpacity": @1.00,
            @"ActiveBarCells": @40,
            @"NextItemCount": @3,
            @"ProgressBarStyle": @"dots",
            @"LayoutMode": @"stacked-local-top",
            @"SegmentGap": @"normal",
            @"CornerStyle": @"rounded",
            @"ShadowStyle": @"none",
            @"Density": @"default",
            @"ShowFlags": @NO,
            @"ShowUTCReference": @NO,
            @"ShowSkyState": @NO,
            @"ShowProgressPercent": @NO,
            @"SelectedMarket": @"local",
        },
        @"Watch Party": @{
            @"DisplayMode": @"single-market",
            @"LocalTheme": @"dracula",
            @"ActiveTheme": @"dracula",
            @"NextTheme": @"dracula",
            @"ColorTheme": @"dracula",
            @"FontSize": @48.0,
            @"ActiveFontSize": @16.0,
            @"NextFontSize": @16.0,
            @"ShowSeconds": @YES,
            @"ShowDate": @YES,
            @"DateFormat": @"short",
            @"TimeFormat": @"24h",
            @"CanvasOpacity": @0.90,
            @"ActiveBarCells": @40,
            @"NextItemCount": @3,
            @"ProgressBarStyle": @"dots",
            @"LayoutMode": @"stacked-local-top",
            @"SegmentGap": @"airy",
            @"CornerStyle": @"rounded",
            @"ShadowStyle": @"glow",
            @"Density": @"spacious",
            @"ShowFlags": @YES,
            @"ShowUTCReference": @YES,
            @"ShowSkyState": @YES,
            @"ShowProgressPercent": @NO,
            @"SelectedMarket": @"nyse",
        },
    };
}

NSArray<NSString *> *profileManagedKeys(void) {
    return @[
        @"DisplayMode", @"LocalTheme", @"ActiveTheme", @"NextTheme", @"ColorTheme",
        @"FontName", @"FontSize", @"ShowSeconds", @"ShowDate", @"TimeFormat",
        @"DateFormat", @"CanvasOpacity", @"ProgressBarStyle", @"LayoutMode", @"SegmentGap", @"CornerStyle", @"ShadowStyle",
        @"ActiveBarCells", @"NextItemCount", @"SelectedMarket",
        @"ActiveFontSize", @"NextFontSize", @"ShowFlags", @"Density",
        @"ShowUTCReference", @"ShowSkyState", @"ShowProgressPercent",
    ];
}
