#!/usr/bin/env bun
/**
 * Tests for the commit-message exposure guard and the three identifier
 * detectors added to the shared detector alongside it.
 *
 * Every positive fixture below is a SYNTHETIC STAND-IN whose SHAPE matches the
 * real incident (a scrub commit that enumerated what it removed) while its
 * VALUE is invented for this file. Using the real values here would repeat the
 * exact mistake the guard exists to stop — this test file is itself published.
 *
 * The negative cases carry equal weight. This guard runs on every commit in a
 * repo whose release notes are full of semver strings, git SHAs, issue numbers
 * and example hostnames; one false block and the operator reaches for
 * `--no-verify` permanently, which loses the credential gate too.
 *
 * SECRET-SCAN-OK: synthetic non-live fixtures for the commit-message guard suite
 * PII-SCAN-OK
 */

import { describe, expect, test } from "bun:test";
import {
  detectAwsAccountIdentifiers,
  detectHardwareMacAddresses,
  detectClientScopedWorkersDevHostnames,
  detectThirdPartyPiiExposure,
  detectVaultItemIdentifiers,
} from "../plugins/itp-hooks/hooks/lib/secret-and-pii-exposure-detector.ts";
import {
  buildCommitMessageCredentialBlock,
  buildCommitMessagePiiReminder,
  extractRecordedCommitMessage,
  hasValidEscapeHatch,
  isAutoGeneratedCommitSubject,
  parseArguments,
  scanCommitMessage,
} from "./commit-message-exposure-guard.ts";

// Synthetic, never-issued.
const SYNTHETIC_TELEGRAM_TOKEN = "8123456789:AAF3n7Qz1kLpXyR2vBcD4eF5gH6iJ7kL8mN";
const SYNTHETIC_AWS_ACCOUNT_ID = "409377215884";
// 26 chars, all within the [a-z2-7] base32 alphabet 1Password item IDs use.
const SYNTHETIC_VAULT_ITEM_ID = "k3jq7wxzpl2xnv7bd4rt6ycm5a";

describe("AWS account ID detector", () => {
  test("fires on a 12-digit run beside an AWS cue — the shape that leaked twice", () => {
    const findings = detectAwsAccountIdentifiers(
      `removed the company AWS account id ${SYNTHETIC_AWS_ACCOUNT_ID} from the doc`,
    );
    expect(findings).toHaveLength(1);
    expect(findings[0]?.kind).toBe("aws-account-id");
  });

  test("fires inside an ARN", () => {
    expect(
      detectAwsAccountIdentifiers(`arn:aws:iam::${SYNTHETIC_AWS_ACCOUNT_ID}:role/deploy`),
    ).toHaveLength(1);
  });

  test("never echoes the full account number", () => {
    const findings = detectAwsAccountIdentifiers(`aws account ${SYNTHETIC_AWS_ACCOUNT_ID}`);
    expect(findings[0]?.excerpt).not.toContain(SYNTHETIC_AWS_ACCOUNT_ID);
  });

  test("does NOT fire on a 12-digit run with no AWS cue", () => {
    expect(detectAwsAccountIdentifiers("row count 409377215884 after backfill")).toHaveLength(0);
    expect(detectAwsAccountIdentifiers("epoch nanos 173512908411 logged")).toHaveLength(0);
  });

  test("does NOT fire on AWS's own documentation filler", () => {
    expect(detectAwsAccountIdentifiers("arn:aws:iam::123456789012:role/x")).toHaveLength(0);
    expect(detectAwsAccountIdentifiers("aws account id 000000000000")).toHaveLength(0);
  });

  test("does NOT fire on a git SHA, semver or issue number near AWS words", () => {
    expect(detectAwsAccountIdentifiers("aws deploy at 4f3c9ab1d2e8 (v27.0.1, #1204)")).toHaveLength(
      0,
    );
  });
});

describe("workers.dev hostname detector", () => {
  test("fires on a project.account.workers.dev host — names client and deal", () => {
    const findings = detectClientScopedWorkersDevHostnames(
      "removed the hostname quarry-ledger.northvale-partners.workers.dev from the README",
    );
    expect(findings).toHaveLength(1);
    expect(findings[0]?.kind).toBe("client-scoped-workers-dev-hostname");
  });

  test("does NOT fire on a single-label host, which names no account", () => {
    expect(detectClientScopedWorkersDevHostnames("deployed to gateway.workers.dev")).toHaveLength(0);
  });

  test("does NOT fire on documentation placeholders", () => {
    expect(
      detectClientScopedWorkersDevHostnames("see <name>.<account>.workers.dev for the URL"),
    ).toHaveLength(0);
    expect(
      detectClientScopedWorkersDevHostnames("example: my-worker.example.workers.dev"),
    ).toHaveLength(0);
    expect(detectClientScopedWorkersDevHostnames("hello.my.workers.dev")).toHaveLength(0);
  });
});

describe("vault item identifier detector", () => {
  test("fires on a 26-char base32 id beside a 1Password cue", () => {
    const findings = detectVaultItemIdentifiers(
      `dropped the 1Password item id ${SYNTHETIC_VAULT_ITEM_ID} from the registry`,
    );
    expect(findings).toHaveLength(1);
    expect(findings[0]?.kind).toBe("vault-item-identifier");
  });

  test("fires on an op:// reference", () => {
    expect(
      detectVaultItemIdentifiers(`op://Private/${SYNTHETIC_VAULT_ITEM_ID}/credential`),
    ).toHaveLength(1);
  });

  test("does NOT fire on the same shape with no vault cue", () => {
    expect(detectVaultItemIdentifiers(`build hash ${SYNTHETIC_VAULT_ITEM_ID} archived`)).toHaveLength(
      0,
    );
  });

  test("does NOT fire on a placeholder", () => {
    expect(detectVaultItemIdentifiers("1Password item id <your-item-id>")).toHaveLength(0);
  });
});

describe("commit message extraction", () => {
  test("drops git comment lines", () => {
    expect(
      extractRecordedCommitMessage("fix: thing\n\n# Please enter the commit message\n# On branch x"),
    ).toBe("fix: thing\n");
  });

  test("drops everything below the --verbose scissors line", () => {
    const raw = [
      "fix: thing",
      "",
      "# ------------------------ >8 ------------------------",
      "diff --git a/x b/x",
      `-TELEGRAM_BOT_TOKEN=${SYNTHETIC_TELEGRAM_TOKEN}`,
    ].join("\n");
    const extracted = extractRecordedCommitMessage(raw);
    expect(extracted).not.toContain("TELEGRAM");
    // Critical: a commit that REMOVES a leaked value must not be blocked by it.
    expect(scanCommitMessage(raw).credentialFindings).toHaveLength(0);
  });
});

describe("skip rules", () => {
  test.each(["Merge branch 'main'", "Revert \"feat: x\"", "fixup! feat: x", "squash! feat: x"])(
    "%s is treated as auto-generated",
    (subject) => {
      expect(isAutoGeneratedCommitSubject(subject)).toBe(true);
    },
  );

  test("a normal conventional subject is not auto-generated", () => {
    expect(isAutoGeneratedCommitSubject("feat(itp-hooks): add guard")).toBe(false);
  });

  test("an empty message is skipped rather than scanned", () => {
    expect(scanCommitMessage("\n# comment only\n").skipped).toBe(true);
  });
});

describe("escape hatch", () => {
  test("SECRET-SCAN-OK with a >=10-char reason suppresses", () => {
    expect(hasValidEscapeHatch("chore: x\n\nSECRET-SCAN-OK: synthetic fixture for the suite")).toBe(
      true,
    );
    expect(
      scanCommitMessage(
        `chore: x\n\nSECRET-SCAN-OK: synthetic fixture for the suite\ntoken ${SYNTHETIC_TELEGRAM_TOKEN}`,
      ).credentialFindings,
    ).toHaveLength(0);
  });

  test("a bare marker with no reason does NOT suppress", () => {
    expect(hasValidEscapeHatch("chore: x\n\nSECRET-SCAN-OK")).toBe(false);
    expect(hasValidEscapeHatch("chore: x\n\nSECRET-SCAN-OK: short")).toBe(false);
  });
});

describe("commit-message scan — severity split", () => {
  test("BLOCKS a message carrying a live-shaped credential", () => {
    const result = scanCommitMessage(
      `chore(security): scrub secrets\n\nRemoved TELEGRAM_BOT_TOKEN=${SYNTHETIC_TELEGRAM_TOKEN} from the ADR.`,
    );
    expect(result.credentialFindings.length).toBeGreaterThan(0);
    const block = buildCommitMessageCredentialBlock(result.credentialFindings);
    expect(block).toContain("BLOCKED");
    expect(block).not.toContain("AAF3n7Qz1kLpXyR2vBcD4e");
  });

  test("REMINDS but does not block on the enumerated-identifier scrub shape", () => {
    // This is the incident, reconstructed with synthetic values: a scrub commit
    // that lists everything it removed, which semantic-release then publishes.
    const result = scanCommitMessage(
      [
        "chore(docs): scrub client identifiers",
        "",
        "Removed the following from the design spec:",
        `  - AWS account id ${SYNTHETIC_AWS_ACCOUNT_ID}`,
        "  - hostname quarry-ledger.northvale-partners.workers.dev",
        `  - 1Password item id ${SYNTHETIC_VAULT_ITEM_ID}`,
        "  - contact j.doe@acmewidgets.co.uk, phone: 437-291-6053",
      ].join("\n"),
    );
    expect(result.credentialFindings).toHaveLength(0);
    const kinds = result.piiFindings.map((f) => f.kind);
    expect(kinds).toContain("aws-account-id");
    expect(kinds).toContain("client-scoped-workers-dev-hostname");
    expect(kinds).toContain("vault-item-identifier");
    expect(kinds).toContain("third-party-email");
    expect(kinds).toContain("third-party-phone-number");
  });

  test("the reminder explains the semantic-release republication mechanism", () => {
    const reminder = buildCommitMessagePiiReminder(
      detectThirdPartyPiiExposure(`aws account id ${SYNTHETIC_AWS_ACCOUNT_ID}`),
    );
    expect(reminder).toContain("semantic-release");
    expect(reminder).not.toContain(SYNTHETIC_AWS_ACCOUNT_ID);
  });

  test("the category-only phrasing this rule asks for is silent", () => {
    const result = scanCommitMessage(
      [
        "chore(docs): scrub client identifiers from the design spec",
        "",
        "Categories removed, deliberately not enumerated by value:",
        "  - two client phone numbers",
        "  - one client name and honorific",
        "  - one cloud account identifier",
        "  - one vault item identifier",
      ].join("\n"),
    );
    expect(result.credentialFindings).toHaveLength(0);
    expect(result.piiFindings).toHaveLength(0);
  });
});

describe("false-positive floor — ordinary release-shaped commit prose", () => {
  test.each([
    "fix(itp-hooks): correct off-by-one in line numbering\n\nCloses #1204. Follows up on 4f3c9ab.",
    "chore(release): v27.0.2 [skip ci]\n\nBumps 26.4.1 -> 27.0.2 across 42 plugins.",
    "docs: use <redacted> and example.com placeholders in the vendor spec",
    "test: cover the 555-0142 reserved range and support@example.org",
    "feat: retry 3 times with 1000-2000-4000 ms backoff",
    "build(deps): bump typescript from 7.0.1 to 7.0.4",
    "refactor: drop the 123456789012 fixture from the aws mock",
  ])("stays silent on %s", (message) => {
    const result = scanCommitMessage(message);
    expect(result.credentialFindings).toHaveLength(0);
    expect(result.piiFindings).toHaveLength(0);
  });
});

describe("argument parsing", () => {
  test("requires --message-file", () => {
    expect(parseArguments([]).kind).toBe("usage-error");
  });

  test("rejects an unknown flag rather than silently scanning", () => {
    // A mis-invocation that exits 0 is an untraceable bypass.
    expect(parseArguments(["--path", "x"]).kind).toBe("usage-error");
  });

  test("accepts the git-hook invocation shape", () => {
    const parsed = parseArguments(["--message-file", "/tmp/COMMIT_EDITMSG"]);
    expect(parsed.kind).toBe("check");
  });

  test("--help short-circuits", () => {
    expect(parseArguments(["--help"]).kind).toBe("help");
  });
});

describe("detectHardwareMacAddresses", () => {
  // A MAC is globally unique and permanent, so it names one physical device
  // across every network it joins; a Wi-Fi BSSID additionally resolves to a
  // street address in public wardriving databases. Both fixtures below are
  // invented, using an OUI prefix assigned to no vendor.
  test("flags a colon-separated hardware address", () => {
    const findings = detectHardwareMacAddresses("adapter 3e:91:c7:0a:4b:d2 came up");
    expect(findings).toHaveLength(1);
    expect(findings[0]?.kind).toBe("hardware-mac-address");
  });

  test("flags the hyphen-separated form too", () => {
    expect(detectHardwareMacAddresses("MAC 3E-91-C7-0A-4B-D2")).toHaveLength(1);
  });

  test("echoes only the outer octets, never the whole address", () => {
    const [finding] = detectHardwareMacAddresses("bssid 3e:91:c7:0a:4b:d2");
    expect(finding?.excerpt).toBe("3e:…:d2");
    // The point of a redacted excerpt is that the reminder cannot itself
    // republish the identifier it is warning about.
    expect(finding?.excerpt).not.toContain("91");
    expect(finding?.excerpt).not.toContain("c7");
  });

  test("ignores structural constants that name no device", () => {
    expect(detectHardwareMacAddresses("unset 00:00:00:00:00:00")).toHaveLength(0);
    expect(detectHardwareMacAddresses("broadcast ff:ff:ff:ff:ff:ff")).toHaveLength(0);
    expect(detectHardwareMacAddresses("filler aa:aa:aa:aa:aa:aa")).toHaveLength(0);
  });

  test("ignores the RFC 7042 documentation ranges", () => {
    // These exist precisely so examples need not borrow a real device.
    expect(detectHardwareMacAddresses("doc 00:00:5e:00:53:11")).toHaveLength(0);
    expect(detectHardwareMacAddresses("doc 01:00:5e:90:10:07")).toHaveLength(0);
  });

  test("ignores traditional hex-word placeholders", () => {
    expect(detectHardwareMacAddresses("de:ad:be:ef:00:01")).toHaveLength(0);
    expect(detectHardwareMacAddresses("ca:fe:ba:be:12:34")).toHaveLength(0);
  });

  test("does not match a longer hex run printed in octet pairs", () => {
    // A hash or key fingerprint must not be mistaken for an address, which is
    // what the boundary lookarounds are for.
    expect(
      detectHardwareMacAddresses("sha 3e:91:c7:0a:4b:d2:7f:65:11:9c:04:ab"),
    ).toHaveLength(0);
  });

  test("stays silent on ordinary release prose", () => {
    // The false-positive floor: this guard runs on every commit, and one bad
    // block sends the operator to --no-verify permanently.
    expect(
      detectHardwareMacAddresses("bump v30.1.0 → v30.2.0, closes #412, sha 89828c3e"),
    ).toHaveLength(0);
  });
});
